### ISSUE TITLE
Recurrent lstm state being reshaped incorrectly

### ISSUE THREAD

**Issue by kolbytn** [Stable-Baselines-Team/stable-baselines3-contrib#111]
While using sb3-contrib for recurrent ppo, I noticed what I believe to be an error in the retrieval of the lstm states.

Lines 216-225 and 358-376 of `sb3_contrib/common/recurrent/buffers.py` use a reshape operation where I believe they should be doing a transpose/swapaxes.

Original code:
```
lstm_states_pi = (
    # (n_steps, n_layers, n_envs, dim) -> (n_layers, n_seq, dim)
    self.hidden_states_pi[batch_inds][self.seq_start_indices].reshape(n_layers, n_seq, -1),
    self.cell_states_pi[batch_inds][self.seq_start_indices].reshape(n_layers, n_seq, -1),
)
lstm_states_vf = (
    # (n_steps, n_layers, n_envs, dim) -> (n_layers, n_seq, dim)
    self.hidden_states_vf[batch_inds][self.seq_start_indices].reshape(n_layers, n_seq, -1),
    self.cell_states_vf[batch_inds][self.seq_start_indices].reshape(n_layers, n_seq, -1),
)
``` 

The array shapes here actually start as `(n_envs*n_steps, n_layers, dim)` (the commented sizes are incorrect), then are sliced to `(n_seq, n_layers, dim)`. From there I think the axes should be swapped rather than reshaped into `(n_layers, n_seq, dim)`.

My proposed change:
```
lstm_states_pi = (
    # (n_envs*n_steps, n_layers, dim) -> (n_seq, n_layers, dim) -> (n_layers, n_seq, dim)
    self.hidden_states_pi[batch_inds][self.seq_start_indices].swapaxes(0, 1),
    self.cell_states_pi[batch_inds][self.seq_start_indices].swapaxes(0, 1)
)
lstm_states_vf = (
    # (n_envs*n_steps, n_layers, dim) -> (n_seq, n_layers, dim) -> (n_layers, n_seq, dim)
    self.hidden_states_vf[batch_inds][self.seq_start_indices].swapaxes(0, 1),
    self.cell_states_vf[batch_inds][self.seq_start_indices].swapaxes(0, 1)
)
``` 

Unfortunately my experiments don't show a noticeable difference in learning curves because this data is only used for initializing the lstm state. However, the ouput of the two methods is not equivalent when n_layers>1 and n_seq>1.

Let me know if I'm missing something or if this is a valid fix. Thanks!

**Comment by araffin** [comment]
Hello,
thanks for reporting the issue, i'll try to have a look tomorrow;)
good news anyway that it doesn't affect much performance.

**Comment by araffin** [comment]
Looking again at it, you are right, the shape comments are outdated but I think the operation seems correct.
The swap axes was done here:
https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/7993b75781d7f43262c80c023cd83cfe975afe3a/sb3_contrib/common/recurrent/buffers.py#L151-L154

And then flattened here:
https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/7993b75781d7f43262c80c023cd83cfe975afe3a/sb3_contrib/common/recurrent/buffers.py#L156-L158

So the operation here:
https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/7993b75781d7f43262c80c023cd83cfe975afe3a/sb3_contrib/common/recurrent/buffers.py#L218

actually does:
```python
# 1. (n_envs * n_steps, n_layers, dim) -> (batch_size, n_layers, dim) 
# 2. (batch_size, n_layers, dim)  -> (n_seq, n_layers, dim) 
# 3. (n_seq, n_layers, dim) -> (n_layers, n_seq, dim)
```

> I think the axes should be swapped rather than reshaped

I think it is equivalent here (did a quick try, will try again later).

**Comment by araffin** [comment]
So, after more trials, `swap_axes` and `reshape` are equivalents only when `n_layers=1` (which is luckily the case by default).

Do you want to submit a PR that solves this issue?

**Comment by araffin** [comment]
I think there might be another bug (ratio of PPO is not one the first iteration..)
