### ISSUE TITLE
How to visualize RecurrentPPO policy network architecture

### ISSUE THREAD

**Issue by ashleychung830** [Stable-Baselines-Team/stable-baselines3-contrib#114]
Hi, I was wondering if there is any way to visualize the policy architecture for RecurrentPPO beyond just using model.policy or tensorboard?

**Comment by araffin** [comment]
> visualize the policy architecture for RecurrentPPO beyond just using model.policy or tensorboard?

best is to use ipython debugger or `print(model.policy)`.

For a more high level, you can take a look at the documentation: https://stable-baselines3.readthedocs.io/en/master/guide/custom_policy.html
