### ISSUE TITLE
[QUESTION] lstm_states for value prediction and action evaluation

### ISSUE THREAD

**Issue by dylanprins** [Stable-Baselines-Team/stable-baselines3-contrib#117]
Hi!

We are using a Recurrent Actor Critic Policy (RecurrentPPO algorithm)

We have our own evaluate function, where we of course use the original `model.predict()` function which returns the preferred action and the next hidden state.

Let's call the returned hidden state `lstm_states`.
In our evaluation function we also want to obtain the predicted value (obtained with `model.policy.predict_values`) and we want to see how the actions were evaluated (with `model.policy.evaluate_actions`).

To obtain these, both the functions need `lstm_states`. Question is, can we simply use the hidden `lstm_states` returned by the `model.predict() `function as input for both `model.policy.predict_values` and `model.policy.evaluate_actions`?

We use a seperate critic lstm (`self.lstm_cricic`), meaning that in `model.policy.predict_values`
`latent_vf, lstm_states_vf = self._process_sequence(features, lstm_states, episode_starts, self.lstm_critic)` is called.

In `model.policy.evaluate_actions` we would call two things:
`latent_pi, _ = self._process_sequence(features, lstm_states.pi, episode_starts, self.lstm_actor)` and `latent_vf, _ = self._process_sequence(features, lstm_states.vf, episode_starts, self.lstm_critic)`

Is the by `model.predict()` returned `lstm_states` the proper input for `model.policy.predict_values`? (I dont think so) and is it also the proper input for `model.policy.evaluate_actions`? The latter distinguishes between `lstm_states` for the pi and vf.

So, most probably we need different hidden `lstm_states` for the vf and pi (where `model.policy.predict_values` uses the vf hidden states?). Which one is returned by the `model.predict()` function? Those from pi?

Summary of questions:
- Does `model.predict()` return the vf or pi hidden lstm states?
- Does `model.policy.predict_values` use the vf or pi hidden lstm states? (vf i suppose)
- Can I obtain `lstm_states` with both vf and pi as expected by `model.policy.evaluate_actions` from anywhere? If not, how do i build it myself for evaluation? The examples only show a `action, lstm_states = model.predict()` but that does not return for both vf and pi.

**Comment by araffin** [comment]
Hello,

> Does model.predict() return the vf or pi hidden lstm states?

https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/c75ad7dd58b7634e48c9e345fca8ebb06af3495e/sb3_contrib/common/recurrent/policies.py#L351

pi hidden states (but they are the same when the LSTM is shared of course).

> Does model.policy.predict_values use the vf or pi hidden lstm states? (vf i suppose)

vf when not shared with pi:
https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/c75ad7dd58b7634e48c9e345fca8ebb06af3495e/sb3_contrib/common/recurrent/policies.py#L319-L324

> Can I obtain lstm_states with both vf and pi as expected by model.policy.evaluate_actions from anywhere? 

you can first initialize them with zeros:
https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/36aeae18b5c026930b4acf228d86fcfa9c50cfc3/sb3_contrib/ppo_recurrent/ppo_recurrent.py#L163-L173

in the predict (for pi only):
https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/c75ad7dd58b7634e48c9e345fca8ebb06af3495e/sb3_contrib/common/recurrent/policies.py#L383-L386

and then update them in the loop
https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/36aeae18b5c026930b4acf228d86fcfa9c50cfc3/sb3_contrib/ppo_recurrent/ppo_recurrent.py#L239-L243

**Comment by dylanprins** [comment]
Thanks for the response! :)
