### ISSUE TITLE
Implement QR-DQN

### ISSUE THREAD

**Issue by araffin** [Stable-Baselines-Team/stable-baselines3-contrib#12]
Paper: https://arxiv.org/abs/1710.10044

@ku2482 Please tell us if you want to work on that ;)

**Comment by ku2482** [comment]
@araffin 
Yes, I'd love to.
When is version 1.0 expected to be released so that I can start implementing it?

Thanks :)

**Comment by araffin** [comment]
> When is version 1.0 expected to be released so that I can start implementing it?

You can start now ;) (we are only waiting for minor details to release v1.0)

**Comment by ku2482** [comment]
I see. I'm gonna work on it as soon as possible.
Can I implement QR-DQN roughly in a week or two, and then we can discuss it again?

**Comment by araffin** [comment]
> Can I implement QR-DQN roughly in a week or two, and then we can discuss it again?

Perfect, best would to open a WIP PR ;)
Unless you have something special in mind, we can then discuss on the PR page.
But the general guidelines are:
- take a look at DQN and other SB3 implementations (to get the spirit of variable names and how algorithms are implemented, you can take a look at the developer guide too in the doc)
- for default hyperparameters, please use the one from the original paper
- you may re-use the `quantile_loss` from `TQC` and then put it in `common/utils.py`
- don't forget to provide a benchmark (one or two Atari games + one classic control task) that matches the original results  (if you have the compute resources, otherwise, I can help you for Atari games)
- don't forget to read our CONTRIBUTING guide of contrib repo carefully (regarding tests and documentation)
