### ISSUE TITLE
v1.6.2 doesn't contain the deprecations as documented

### ISSUE THREAD

**Issue by derek-rocheleau** [Stable-Baselines-Team/stable-baselines3-contrib#132]
v1.6.2 release description names some deprecations that were made. These deprecations were not made in code until the following day, so they are not contained in the release. I request a new release which contains these deprecations.

**Comment by araffin** [comment]
Hello,

A pre-release is already on pypi: https://pypi.org/project/sb3-contrib/1.7.0a11/
Stable release should come soon (i want to deprecate shared mlp networks first).

**Comment by derek-rocheleau** [comment]
Thank you. Somehow I was using stable_baseline 1.7.0a11 but sb3_contrib 1.6.2. Once I upgraded the latter to 1.7.0a11 the issue resolved.
