### ISSUE TITLE
[Feature request] Recurrent PPO for sequence observation space

### ISSUE THREAD

**Issue by younik** [Stable-Baselines-Team/stable-baselines3-contrib#135]
From version 0.26, gym supports `sequence` as observation space (https://github.com/openai/gym/pull/2968)
After https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/pull/71, I think it would be useful to adapt the current version of Recurrent PPO to work with sequences and unroll them as well.

In my case, I work with weather data, but I can take action after a timespan, let's say every month. This means I observe a time series every step (30 days of weather) and I would like to unroll them as well.

I don't see an easy workaround for this case with the current API.

**Comment by younik** [comment]
> how much work do you think it is? 
> how much additional complexity would it represent? 
> I assume you would volunteer to add support?

I am implementing it; mainly `RecurrentActorCriticPolicy._process_sequence` should be adapted to accept a `(batch, sequence length, features)` tensor, and the `forward_actor` / `forward_critic` calls to use only the last latent of the step unrolling.
This adds a bit more complexity.

Also, the feature extractor should process the Sequence as a batch.

> for your problem, it sounds like 1D CNN or transformer-like features extractor might also be a good fit (defining your space as (n_days, n_features) or n_days x dim_features, just like frame-stacking)

Yes, true, thanks for the suggestion! Still, it would be good to keep the state from the last step, while unrolling the current observation. Of course, I can accumulate the observation, but this is not optimal.

**Comment by younik** [comment]
@araffin you can see the changes here: https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/compare/master...younik:stable-baselines3-contrib:master

It still misses changes to the feature extractor that should add a new batch dimension for sequences observation

**Comment by araffin** [comment]
thanks, could you create a draft PR (that makes it easier to find/take a look at)
