### ISSUE TITLE
Getting wrapper warning during training and then training does not work

### ISSUE THREAD

**Issue by gowthamnatarajan** [Stable-Baselines-Team/stable-baselines3-contrib#143]
Here is the code:
![image](https://user-images.githubusercontent.com/5133248/216761318-1795ddb8-23ee-4a47-935a-f73f8e438d8f.png)

The training begins, and initially is picks the actions randomly as expected. But after a few seconds I get the following warning:

![image](https://user-images.githubusercontent.com/5133248/216761473-65900b91-ba48-40fa-ba24-eb5b2cc48a43.png)

And then after this it always picks just one action over and over again and nothing happens. It no longer picks actions in random so it does not learn anything.
What could be causing this? The same error happens even with the regular PPO algorithm in the sb3 package as well.

**Comment by araffin** [comment]
Hello,
please fill the issue template completely (minimal working example and markdown code block are missing).
This is the second I'm asking you (https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/142#issuecomment-1412002247), if you continue to not follow basic rules to ask for help, i'll have to close any new issue without reading.

PS: i need to add custom gym env issue template in sb3 contrib, but can find/copy it from sb3
