### ISSUE TITLE
[Feature request] Support python 3.11

### ISSUE THREAD

**Issue by wkoot** [Stable-Baselines-Team/stable-baselines3-contrib#144]
Please move to support python 3.11

Requirement `gym` can be moved to `gymnasium`, which supports python 3.11. Perhaps  #71 is needed?

**Comment by araffin** [comment]
Hello,

> Please move to support python 3.11

the code is python only, so it is compatible with python 3.11. The only thing that might be problematic are the dependencies.

as mentioned in https://github.com/DLR-RM/stable-baselines3/pull/780, you can already use latest version including https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/pull/71 too.
The install instructions are similar (and are linked in the PR):
```
pip install git+https://github.com/Stable-Baselines-Team/stable-baselines3-contrib@feat/new-gym-version
```

(as we do in the RL Zoo: https://github.com/DLR-RM/rl-baselines3-zoo/pull/256)

**Comment by araffin** [comment]
done
