### ISSUE TITLE
the trace is from a new failing test. In the test I'm trying to mask environment with a dict observation space and multidiscrete action space.

### ISSUE THREAD

**Issue by zbenmo** [Stable-Baselines-Team/stable-baselines3-contrib#148]
sb3_contrib/common/maskable/distributions.py:58: RuntimeError
=================================================== warnings summary ===================================================
../qwertyenv/venv/lib/python3.8/site-packages/_pytest/config/__init__.py:1294
  /home/oren/projects/qwertyenv/venv/lib/python3.8/site-packages/_pytest/config/__init__.py:1294: PytestConfigWarning: Unknown config option: env

    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

tests/test_invalid_actions.py::test_callback
  /home/oren/projects/qwertyenv/venv/lib/python3.8/site-packages/stable_baselines3/common/callbacks.py:684: TqdmExperimentalWarning: rich is experimental/alpha
    self.pbar = tqdm(total=self.locals["total_timesteps"] - self.model.num_timesteps)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=============================================== short test summary info ================================================
FAILED tests/test_invalid_actions.py::test_dict_obs_tougher - RuntimeError: shape '[1, 8]' is invalid for input of size 32
====================================== 1 failed, 15 passed, 2 warnings in 21.19s =======================================

**Comment by araffin** [comment]
Hello,
please use the issue template and markdown code block (that makes it easier for me to analyse and reproduce).

**Comment by zbenmo** [comment]
See #149 (the same issue)
