### ISSUE TITLE
issue about RPPO

### ISSUE THREAD

**Issue by tingtingLiuLiu** [Stable-Baselines-Team/stable-baselines3-contrib#156]
Hello, when the LSTM network is used as the basic unit, the environmental state transition model is used for sampling, and the state sequence of t steps consecutive moments is used as the input of the network (s1,..., st).
How does Recurrent ppo set this value? Can you tell me the code location?
Thanks

**Comment by araffin** [comment]
> the environmental state transition model is used for sampling, and the state sequence of t steps consecutive moments is used as the input of the network (s1,..., st).

you mean where do we create sequences of observations/actions to update the network?
this is done in the buffer: https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/sb3_contrib/common/recurrent/buffers.py#L25 (the code is complex to have a fixed mini-batch size without constrain on the number of envs/steps)

there is a simpler version available in https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/pull/118 but with variable batch size.
