### ISSUE TITLE
TypeError: OnPolicyAlgorithm.__init__() got an unexpected keyword argument 'create_eval_env'

### ISSUE THREAD

**Issue by aleksanderhan** [Stable-Baselines-Team/stable-baselines3-contrib#157]
When I try to run the minimal example here: https://sb3-contrib.readthedocs.io/en/master/modules/ppo_recurrent.html#example
I only get this as a result: 

```bash
$ python example.py 
Traceback (most recent call last):
  File "/home/aleks/example.py", line 6, in <module>
    model = RecurrentPPO("MlpLstmPolicy", "CartPole-v1", verbose=1)
  File "/home/aleks/anaconda3/lib/python3.10/site-packages/sb3_contrib/ppo_recurrent/ppo_recurrent.py", line 102, in __init__
    super().__init__(
TypeError: OnPolicyAlgorithm.__init__() got an unexpected keyword argument 'create_eval_env'

```
Anyone know what this comes from, and how to solve it?

**Comment by araffin** [comment]
Hello,
make sure to have the same version for SB3 and SB3 contrib. In case of doubt, update both to have the latest version.

**Comment by aleksanderhan** [comment]
Thank you, pinning the version to 1.7.0 of the contrib dependency made it work.
