### ISSUE TITLE
How to get activations for layers?

### ISSUE THREAD

**Issue by ashleychung830** [Stable-Baselines-Team/stable-baselines3-contrib#160]
Hi, I was just wondering how to get the activations (outputs of activation function) for a layer in the network? I know in tf/keras this could be done with model.layers() and related functions however RecurrentPPO and RecurrentActorCriticCnnPolicy objects do not support this method in sb3-contrib. I was able to get the overall network architecture with model.policy() and the weights and biases with model.get_parameters() but I was unable to extract the activations. Is there a method within the documentation that allows for this?

**Comment by araffin** [comment]
Hello,
this is more a pytorch questions.
Best is to fork SB3 to do exactly what you want.
We don't store intermediate activations and don't provide api to get them as they are usually not used/useful (except for debugging).

**Comment by ashleychung830** [comment]
thank you! 

```
import numpy as np

from sb3_contrib import RecurrentPPO
from stable_baselines3.common.evaluation import evaluate_policy

model = RecurrentPPO("MlpLstmPolicy", "CartPole-v1", verbose=1)
model.learn(5000)

env = model.get_env()
mean_reward, std_reward = evaluate_policy(model, env, n_eval_episodes=20, warn=False)
print(mean_reward)

model.save("ppo_recurrent")
del model # remove to demonstrate saving and loading

model = RecurrentPPO.load("ppo_recurrent")

obs = env.reset()
# cell and hidden state of the LSTM
lstm_states = None
num_envs = 1
# Episode start signals are used to reset the lstm states
episode_starts = np.ones((num_envs,), dtype=bool)
while True:
    action, lstm_states = model.predict(obs, state=lstm_states, episode_start=episode_starts, deterministic=True)
    obs, rewards, dones, info = env.step(action)
    episode_starts = dones
    env.render()
```

also just checking, for the above example, when using model.predict(), does **lstm_states** refer to the activations of the units that project to the actor/critic feature layers?

**Comment by araffin** [comment]
>  does lstm_states refer to the activations of the units that project to the actor/critic feature layers?

The `lstm_states` refers to the LSTM states (cell and hidden states) of the LSTM of the actor (https://colah.github.io/posts/2015-08-Understanding-LSTMs/).
You can take a look at https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/sb3_contrib/common/recurrent/policies.py#L113

**Comment by ashleychung830** [comment]
Thanks for the reference, this was helpful!

I am attempting to construct a network architecture with two branches after the CNN layers, where there are two LSTMS (one "actor" LSTM and "critic" LSTM) followed by separate actor/critic feature layers. Attached is a diagram of the network I'm trying to achieve:

<img width="281" alt="Screen Shot 2023-03-08 at 7 39 54 PM" src="https://user-images.githubusercontent.com/105668173/223887072-659f989b-91a5-46c0-8f74-3be9725d3306.png">
 
Here is my code where I attempt to instantiate the network (NatureCNN_Rewinput is just my adapated CNN input):
```
policy_kwargs = dict(features_extractor_class= NatureCNN_RewInput, features_extractor_kwargs=dict(features_dim=130), 
                     net_arch = [dict(pi=[64], vf=[64])], normalize_images = True, 
                     lstm_hidden_size = 128, n_lstm_layers = 1, shared_lstm = False, enable_critic_lstm = True)
```
I was unable to figure out a way to visualize the network, but model.policy() yielded this:
<img width="355" alt="Screen Shot 2023-03-08 at 6 39 17 PM" src="https://user-images.githubusercontent.com/105668173/223889121-068f91b7-4b5a-418b-9750-d47ba33e6086.png">

I'm not sure why lstm_actor and lstm_critic appears at the bottom of the components of model.policy()? Does it come after action_net and value_net, or is this list out of order?

With SB2, I could get the network weights through the following code.
```
def get_a2c_model_data(model, env, n_eval_episodes=10, by_ep = False, obses_ep_saved = 10):
    if isinstance(env, VecEnv):
        assert env.num_envs == 1, "You must pass only one environment when using this function"

    actions, rewards, obses, feats, featsPI, featsV, terms, vs, tow_counts = [], [], [], [], [], [], [], [], []
    episode_lengths = np.zeros((n_eval_episodes))
    [graph, sess] = model.get_graph_and_sess()
    state_ph_shape = graph.get_tensor_by_name("input_1/states_ph:0").shape
    dones_ph_shape = graph.get_tensor_by_name("input_1/dones_ph:0").shape
    for ep in range(n_eval_episodes):
        obs = env.reset()
        done = np.zeros((dones_ph_shape))
        state = np.zeros((state_ph_shape))
        episode_length = 0

        while not done:

            if ep < obses_ep_saved:
                obses.append(obs)
            feats.append(graph.get_tensor_by_name("model/concat_2:0").eval(
                {"input/Ob:0":obs, "input_1/dones_ph:0":done
                , "input_1/states_ph:0":state}, session = sess))
            featsPI.append(graph.get_tensor_by_name("model/Tanh_2:0").eval(
                {"input/Ob:0":obs, "input_1/dones_ph:0":done
                , "input_1/states_ph:0":state}, session = sess))
            featsV.append(graph.get_tensor_by_name("model/Tanh_3:0").eval(
                {"input/Ob:0":obs, "input_1/dones_ph:0":done
                , "input_1/states_ph:0":state}, session = sess))
            vs.append(model.value(obs, state = state, mask = done))
            action, state = model.predict(obs, state=state)
            actions.append(action)
            obs, reward, done, info = env.step(action)
            rewards.append(reward)
            terms.append(done[0])
            tows = np.copy(info[0]['tow_counts'])
            tow_counts.append(tows)
            episode_length += 1
         
        episode_lengths[ep] = episode_length
    all_metrics = [actions, rewards, feats, featsPI, featsV, terms, vs, tow_counts]
    if by_ep:
        ep_idx = np.cumsum(episode_lengths)[:-1].astype(int)
        [actions, rewards, feats, featsPI, featsV, terms, vs, tow_counts] = [np.split(np.squeeze(x), ep_idx, axis = 0) for x in all_metrics]
        obses = np.split(np.squeeze(obses), ep_idx[:obses_ep_saved], axis = 0)
    else:
        [actions, rewards, feats, featsPI, featsV,terms, vs, tow_counts] = [np.squeeze(x) for x in all_metrics]
        obses = np.squeeze(obses)
    return [actions, rewards, obses, feats, featsPI, featsV, terms, vs, tow_counts, episode_lengths]
```
However, SB3-contrib doesn't support this since I use a RecurrentPPO object and many of these functions do not work with it. I have been trying to get around this by using model.predict() to get the LSTM state, and use the tensor weights from model.policy() to compute the actor/critic feature layer activations (since they are not directly available). Do you have any advice/other methods for how I can do this?

**Comment by ashleychung830** [comment]
@araffin Hi, just following up on this! I would greatly appreciate any help/insight you might be able to provide as I am not the most familiar with sb3/sb3-contrib documentation. Thank you so much!

**Comment by araffin** [comment]
There is a better answer here to get the activations: https://github.com/DLR-RM/stable-baselines3/issues/1467#issuecomment-1521862748 (related to https://github.com/DLR-RM/stable-baselines3/issues/508 too)

> I'm not sure why lstm_actor and lstm_critic appears at the bottom of the components of model.policy()? Does it come after action_net and value_net, or is this list out of order?

This is just a dictionary, the order is defined here:
https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/sb3_contrib/common/recurrent/policies.py#L230-L257
