### ISSUE TITLE
[Question] What's the best way to store aditional data in transitions for an OffPolicyAlgorithm

### ISSUE THREAD

**Issue by Butanium** [Stable-Baselines-Team/stable-baselines3-contrib#191]
### ❓ Question

Hey, I'm attempting to implement a new algorithm using the `sb3` codebase. This modified version of DQN requires storing additional information to update its weights based on a transition. Specifically, it needs to store $\lambda_t$ and $\lambda_{t+1}$, which are calculated using the following policy:
$$\aleph_{t+1}\gets \text{RescaleAspiration} (s_t,a_t,s_{t+1})$$
$$\lambda_{t+1} = \frac{\aleph_t -  \min_a Q(s_{t+1},a)}{\max_a Q(s_t,a)-\min_a Q(s_{t+1},a)}$$

I want to store the transition $(s_t, \lambda_t, a_t, r_t, s_{t+1}, \lambda_{t+1})$ in the replay buffer `D` instead of the classic $(s_t, a_t, r_t, s_{t+1})$. However, I couldn't find a way to achieve this using the current sb3 codebase, even after examining the `OffPolicyAlgorithm`. I'm not sure if I can do something else than rewriting the `_store_transition` function.

Alternatively, I'm unsure if storing these values directly in the environment is a viable option.

I would greatly appreciate any guidance or assistance you can provide. Thank you!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] If code there is, it is minimal and working
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

> 'm not sure if I can do something else than rewriting the _store_transition function.

yes, that's the way to go. For something that custom, you should fork SB3.
As an alternative, you could try using a callback (cf. doc).

**Comment by Butanium** [comment]
Yes I did look into callback but I couldn't find a hook function I could use in the doc. I don't think I can access the replay buffer from the callback so I'll rewrite the function

**Comment by araffin** [comment]
>  I don't think I can access the replay buffer from the callback so I'll rewrite the function

`self.model.replay_buffer`
and you could use the `_on_step()` hook.

But yes, in your case, having a fork is the better option.

**Comment by Butanium** [comment]
ok thanks !

**Comment by araffin** [comment]
Of course!
