### ISSUE TITLE
[Question] Action mask dimensions for action combinations in a MultiDiscrete space

### ISSUE THREAD

**Issue by npit** [Stable-Baselines-Team/stable-baselines3-contrib#197]
### ❓ Question

I am using a Multidiscrete space of N, M-dimensional vectors. As far as I can see, the `apply_masking` function in `sb3_contrib/common/maskable/distributions.py` is expecting the mask to contain `M + N` elements:

```python
masks = masks.view(-1, sum(self.action_dims))
```
Is there a way to enable / disable different combinations of values across vectors with the MultiDiscrete space? 
E.g. for N=2, M=3, I would like to make the action vector [1, 1] valid, but actions [1, 2] invalid. 
For an `N+M`-sized mask this cannot be done, as you can enable or disable each specific value flatly, regardless of actions on the other vectors.

I suspect this is a design issue and spaces within a MultiDiscrete should be inherently treated as independent.
If so, I should unroll all possible action combinations into a single `M * N` Discrete space. 

If not, is there a workaround to solve that issue instead?

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> Is there a way to enable / disable different combinations of values across vectors with the MultiDiscrete space?

You would probably need a fork of SB3-Contrib.

> I suspect this is a design issue and spaces within a MultiDiscrete should be inherently treated as independent.

yes, related to https://github.com/DLR-RM/stable-baselines3/issues/1599


> If not, is there a workaround to solve that issue instead?

As for https://github.com/DLR-RM/stable-baselines3/issues/1599, using a Discrete action space with M*N actions would be a solution?

**Comment by npit** [comment]
Got it, thanks. Closing.
