### ISSUE TITLE
[Bug]: MaskablePPO ignores stats_window_size argument

### ISSUE THREAD

**Issue by PatrickHelm** [Stable-Baselines-Team/stable-baselines3-contrib#198]
### 🐛 Bug

`MaskablePPO` ignores the `stats_window_size` argument, as it hard-codes the deque length in `_setup_learn()`.

The relevant part of the `_setup_learn()` function in `MaskablePPO` (from https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/sb3_contrib/ppo_mask/ppo_mask.py#L201) looks like:

```
if self.ep_info_buffer is None or reset_num_timesteps:
            # Initialize buffers if they don't exist, or reinitialize if resetting counters
            self.ep_info_buffer = deque(maxlen=100)
            self.ep_success_buffer = deque(maxlen=100)
```

Whereas the relevant part of the `_setup_learn()` function in `BaseAlgorithm` (from https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/base_class.py#L383) looks like:

```
if self.ep_info_buffer is None or reset_num_timesteps:
            # Initialize buffers if they don't exist, or reinitialize if resetting counters
            self.ep_info_buffer = deque(maxlen=self._stats_window_size)
            self.ep_success_buffer = deque(maxlen=self._stats_window_size)
```

So, I think the `maxlen=100` in `MaskablePPO` should be replaced by `maxlen=self._stats_window_size`, as it is in `BaseAlgorithm`.

I could try to set up a Pull Request for this (it would be my first), as it likely has no major implications. 

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
you're right, this argument is fairly recent: https://github.com/DLR-RM/stable-baselines3/pull/1424

> I could try to set up a Pull Request for this (it would be my first), as it likely has no major implications.

Please do =)
(and check that no other algorithm in SB3 contrib should be updated)

**Comment by PatrickHelm** [comment]
Hello, 
I created a Pull Request regarding this issue. Please review it and give me feedback. Thanks.
`MaskablePPO` is the only affected algorithm, as it is the only class overwriting `_setup_learn()`.
