### ISSUE TITLE
[Bug]: inappropriate actions despite the MaskablePPO applied

### ISSUE THREAD

**Issue by koliber31** [Stable-Baselines-Team/stable-baselines3-contrib#200]
### 🐛 Bug

Even though I appied action mask in maskablePPO agent is still making invalid actions. These invalid actions are very rare though. In one of my experiments I encountered 8 invalid actions in 350k timesteps which is around 0.002% of all actions. This percentage is so small that it convinces me that the problem isn't in my mask but in algorithm. 

### To Reproduce

My env is big enought that's hard to provide minimal example so there is link to my repo: https://github.com/koliber31/HexxagonRL/tree/main. All you have to do is download is and run $ python learnhex.py
There will be proper information in terminal if invalid move occurs, but as I said they are extreamly rare.

### System Info

- OS: Windows-10-10.0.19044-SP0 10.0.19044
- Python: 3.10.12
- Stable-Baselines3: 2.0.0
- PyTorch: 2.0.1+cpu
- GPU Enabled: False
- Numpy: 1.25.1
- Cloudpickle: 2.2.1
- Gymnasium: 0.28.1

({'OS': 'Windows-10-10.0.19044-SP0 10.0.19044', 'Python': '3.10.12', 'Stable-Baselines3': '2.0.0', 'PyTorch': '2.0.1+cpu', 'GPU Enabled': 'False', 'Numpy': '1.25.1', 'Cloudpickle': '2.2.1', 'Gymnasium': '0.28.1'}, '- OS: Windows-10-10.0.19044-SP0 10.0.19044\n- Python: 3.10.12\n- Stable-Baselines3: 2.0.0\n- PyTorch: 2.0.1+cpu\n- GPU Enabled: False\n- Numpy: 1.25.1\n- Cloudpickle: 2.2.1\n- Gymnasium: 0.28.1\n')

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
if you don't provide a minimal working example, we cannot help you.
My guess is that things are as expected. The way ppo mask work is by making the invalid actions very unlikely (but not impossible) to be sampled (see associated paper and code).
