### ISSUE TITLE
Maskable PPO selects illegal actions, altough everything looks correct

### ISSUE THREAD

**Issue by DominikRoB** [Stable-Baselines-Team/stable-baselines3-contrib#208]
### ❓ Question

versions below

I am using Maskable PPO and a custom env wrapped in ActionMasker.
Most of the time it works as expected, but occasionally an illegal action is choosen.

```
def mask_fn(env: gym.Env) -> np.ndarray:
    return env.get_legal_actions()

...
env = ActionMasker(env, mask_fn)

```

`env.get_legal_actions()` returns
```
array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False,  True])
```

I checked inside ppo_mask.py and would like to ask if I maybe wrongly used the ActionMasker.

`use_masking` returns true, as expected.

`action_masks = get_action_masks(env)` returns the following action mask for an example situation.
```
array([[False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False, False,  True]])
```
(it is a nested list, is that correct?)

`actions, values, log_probs = self.policy(obs_tensor, action_masks=action_masks)`

Here, actions became `array([1], dtype=int64)` - an illegal action.
I tried to call `self.policy` a few times manually during debug mode - in these situations it works and only returns legal actions.. It seems to be a rare situation.
Any ideas what is happening here?

System:
Windows 10,
python = "^3.9"
stable-baselines3 = "^2.1.0"
sb3-contrib = "^2.1.0"
gymnasium = "^0.29.1"

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

>  Any ideas what is happening here?

How often are illegal actions sampled?

See my answer in https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/200#issuecomment-1657142807

**Comment by DominikRoB** [comment]
It is indeed very rare. I would say it happens after around a few million steps.
I expected the mask to limit the probabilities to 0 for illegal actions..
