### ISSUE TITLE
Predicting actions after using MaskablePPO model outputs invalid action

### ISSUE THREAD

**Issue by vivek-kumar9696** [Stable-Baselines-Team/stable-baselines3-contrib#212]
### ❓ Question

Hi,
I have trained a model using MaskablePPO. My action space is discrete and observation space is Box datatype.
When training the masking is working properly but when I try to predict, the output comes as one of the invalid actions.
I am new to using MaskablePPO, can somebody help with this.
Thanks

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
See documentation and https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/178

**Comment by vivek-kumar9696** [comment]
@araffin Thanks for the help. Missed it in the documentation and code.
