### ISSUE TITLE
[Question] Recurrent PPO evaluation

### ISSUE THREAD

**Issue by CAI23sbP** [Stable-Baselines-Team/stable-baselines3-contrib#218]
### ❓ Question

I am using SB3 and SB3-contrib. but i searched information for sb(tensorflow) how to training and testing recurrent PPO.
In this [link](https://stable-baselines.readthedocs.io/en/master/guide/examples.html) said that we must matching same number of environment between training and testing. 
Why i should do that? Could you tell me why?

P.S. I am using Recurrent PPO in testing env 5, training env 25.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,
this was a limitation of SB2, we lifted it with SB3.

**Comment by CAI23sbP** [comment]
Thank you for your reply
