### ISSUE TITLE
[Question] LSTM observations

### ISSUE THREAD

**Issue by suargi** [Stable-Baselines-Team/stable-baselines3-contrib#230]
### ❓ Question

Hi,

I would like to clarify some doubts about the implementation or usage of LSTM.

In short, LSTM engages with a sequence of observations to enhance predictive capabilities. According to information provided at https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues/183#issuecomment-1640028534, SB3-contrib defines this sequence as the collection of preceding observations. For instance, in an episodic setting like the moon lander scenario, the process initiates from an initial condition, and at each time step, an action is executed. The observation at each time step corresponds to the lunar state, similar to conventional FFNN. However, LSTM policies leverage past observations during training. Is this understanding accurate?

Idea that I would like to implement:
I create a customized environment where, upon receiving an action, it generates a sine response (symbolizing temporal patterns). The agent's task is to determine the subsequent action based on this response. Rather than relying solely on the last temporal value of the sine response, I can incorporate LSTM to utilize information from previous time points, potentially improving predictive capabilities. Consequently, when employing LSTM, the observation presented to the policy network encompasses not just a single snapshot but a series of observations representing recent historical data. This enables the model to grasp temporal dependencies within the dataset. To elaborate, at each time step, the environment supplies a sequence of states to the LSTM, which then produces a new action before progressing to the next step.
Do you think that is possible to implement?

Thank you!

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] If code there is, it is [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014)
- [X] If code there is, it is formatted using the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
> However, LSTM policies leverage past observations during training. Is this understanding accurate?

yes, this is the role of the LSTM states.

>  To elaborate, at each time step, the environment supplies a sequence of states to the LSTM,

you should not need to change anything, SB3 is in charge of creating the sequence.
You also look into alternatives, see https://wandb.ai/sb3/no-vel-envs/reports/PPO-vs-RecurrentPPO-aka-PPO-LSTM-on-environments-with-masked-velocity--VmlldzoxOTI4NjE4 and PPO with frame-stacking.

**Comment by suargi** [comment]
> you should not need to change anything, SB3 is in charge of creating the sequence.

Not entirely sure how. I create a custom environment which will have the method `step`. There I must return the observation for the current step. Ideally for LSTM the observation should consider more than one state, but currently it can only return a single one. Am I missing something?

Thanks for the links.

**Comment by suargi** [comment]
Questions and misconceptions solved.
