### ISSUE TITLE
MaskablePPO Masking Doesn't Work with Big Action Space

### ISSUE THREAD

**Issue by orkunkn** [Stable-Baselines-Team/stable-baselines3-contrib#247]
### 🐛 Bug

When I try to train my agent with a bigger action space (usually around 1400) I get the following error. I tried the solutions found in https://github.com/DLR-RM/stable-baselines3/issues/1596 and #81 which are overwriting the `super().__init__(logits=logits).` line in distributions.py file of sb3-contrib to `super().__init__(logits=logits, validate_args=False)` and changing the dtype to float or double both in my environment and torch's utils.py file's `return F.softmax(logits, dim=-1)` to `return F.softmax(logits, dim=-1, dtype=torch.double),` but they completely blocked the agent's learning. Also, I have tried normalizing the action space manually between 0 and 1 and making the sum of all values in action_masks 1 by making a small adjustment to one value to prevent floating point errors but I got the same error again.

### Code example

import gymnasium as gym
import numpy as np
import networkx as nx
from mtx_to_array import mtx_to_array
from sb3_contrib import MaskablePPO
from sb3_contrib.common.wrappers import ActionMasker

MAX_ACTION_SPACE = 700
MAX_OBS_SPACE = 5000

class GraphEnv(gym.Env):

    def __init__(self, matrix):
        super(GraphEnv, self).__init__()

        self.action_space = gym.spaces.Discrete(MAX_ACTION_SPACE * 2)

        # Observation space contains thin levels, level details and average values in graph
        self.observation_space = gym.spaces.Box(low=0, high=1, shape=(MAX_OBS_SPACE,), dtype=np.float32)
        
    
    def valid_action_mask(self):
        # Initialize the action mask array
        action_masks = np.zeros(MAX_ACTION_SPACE * 2, dtype=int)

        # Set valid masks for the first action based on thin_levels
        for i in self.thin_levels:
            action_masks[i] = 1
            if self.thin_levels.index(i) == 0:
                action_masks[i] = 0
            reverse_index = MAX_ACTION_SPACE * 2 - 1 - i
            action_masks[reverse_index] = 1

        return action_masks

def mask_fn(env):
    return env.valid_action_mask()

matrix = mtx_to_array("mtx_files/bcspwr04.mtx")

env = GraphEnv(matrix)

env = ActionMasker(env, mask_fn)  # Wrap to enable masking

model = MaskablePPO("MlpPolicy", env, verbose=1, learning_rate=0.00025, n_steps=500)

model.learn(total_timesteps=2048*2)

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "c:\Users\user\OneDrive\Desktop\Projects\train_agent.py", line 27, in <module>
    model.learn(total_timesteps=2048*2)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sb3_contrib\ppo_mask\ppo_mask.py", line 466, in learn
    self.train()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sb3_contrib\ppo_mask\ppo_mask.py", line 339, in train
    values, log_prob, entropy = self.policy.evaluate_actions(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sb3_contrib\common\maskable\policies.py", line 349, in evaluate_actions
    distribution.apply_masking(action_masks)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sb3_contrib\common\maskable\distributions.py", line 167, in apply_masking
    self.distribution.apply_masking(masks)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\sb3_contrib\common\maskable\distributions.py", line 68, in apply_masking
    super().__init__(logits=logits)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\distributions\categorical.py", line 70, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\distributions\distribution.py", line 68, in __init__
    raise ValueError(
ValueError: Expected parameter probs (Tensor of shape (64, 1400)) of distribution MaskableCategorical(probs: torch.Size([64, 1400]), logits: torch.Size([64, 1400])) to satisfy the constraint Simplex(), but found invalid values:
tensor([[0.0007, 0.0007, 0.0007,  ..., 0.0007, 0.0007, 0.0007],
        [0.0007, 0.0007, 0.0007,  ..., 0.0007, 0.0007, 0.0007],
        [0.0007, 0.0007, 0.0007,  ..., 0.0007, 0.0007, 0.0007],
        ...,
        [0.0007, 0.0007, 0.0007,  ..., 0.0007, 0.0007, 0.0007],
        [0.0007, 0.0007, 0.0007,  ..., 0.0007, 0.0007, 0.0007],
        [0.0007, 0.0007, 0.0007,  ..., 0.0007, 0.0007, 0.0007]],
       grad_fn=<SoftmaxBackward0>)
```

### System Info

Describe how the library was installed: pip
- Python: 3.12.3
- Stable-Baselines3: 2.3.0
- sb3-contrib: 2.3.0
- PyTorch: 2.2.2+cpu
- Numpy: 1.26.4
- Gymnasium: 0.29.1

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I have checked my env using the env checker
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by orkunkn** [comment]
I tried the solution found in [https://discuss.pytorch.org/t/distributions-categorical-fails-with-constraint-simplex-but-manual-check-passes/163209/10](url) which is adding the following code in my environment: `from torch.distributions import Distribution
Distribution.set_default_validate_args(False)` and it seems like the problem is solved. I will edit this issue if the problem persists or creates another problem in the future.

**Comment by mwalidcharrwi** [comment]
Hi @orkunkn , did you find another solution/work around beside the code placed in the previous comment?

**Comment by orkunkn** [comment]
Hi @mwalidcharrwi, unfortunately I couldn't. I used this solution in my project and I stopped working on it a few months ago.

**Comment by mwalidcharrwi** [comment]
Alright, thanks for your swift response. @orkunkn
