### ISSUE TITLE
[Bug]: FutureWarning: You are using `torch.load` with `weights_only=False`

### ISSUE THREAD

**Issue by drulye** [Stable-Baselines-Team/stable-baselines3-contrib#254]
### 🐛 Bug

FutureWarning: You are using `torch.load` with `weights_only=False`

### To Reproduce

```python
model = RecurrentPPO.load(
    path=model_path,
    env=env,
    device="cuda",
    custom_objects=None,
    print_system_info=False,
    force_reset=True,
    tensorboard_log=TENSORBOARD_LOG,
)
```

### Relevant log output / Error message

```shell
/home/user/anaconda3/lib/python3.12/site-packages/torch/storage.py:414: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(io.BytesIO(b))
```

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/issues) in the repo
- [X] I have read the [documentation](https://sb3-contrib.readthedocs.io/en/master/)
- [X] I have provided a [minimal and working](https://github.com/DLR-RM/stable-baselines3/issues/982#issuecomment-1197044014) example to reproduce the bug
- [X] I've used the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) for both code and stack traces.

**Comment by araffin** [comment]
Hello,

> System Info

Please provide that (there was instructions in the template).
It should not be the case with the latest version of SB3 normally.

See related issue and PR: https://github.com/DLR-RM/stable-baselines3/issues/1852 (I think we now pass explicitly  `weight_only=False` which should not trigger the warning)

**Comment by araffin** [comment]
thanks, I can reproduce using PyTorch 2.4+ and latest SB3 version:

```python

from sb3_contrib import RecurrentPPO

model = RecurrentPPO("MlpLstmPolicy", "Pendulum-v1")
model.save("/tmp/ppo_cart")
RecurrentPPO.load("/tmp/ppo_cart.zip")
```

I guess it comes from `_last_lstm_states` which are automatically pickled using torch.

quick fix: `del model._last_lstm_states` before saving.

Better fix (I'll try to submit a PR soon):
```python
    def _excluded_save_params(self) -> List[str]:
        return super()._excluded_save_params() + ["_last_lstm_states"]  # noqa: RUF005
```
