### ISSUE TITLE
[Question] TQC's CPU Usage

### ISSUE THREAD

**Issue by bradleypick** [Stable-Baselines-Team/stable-baselines3-contrib#52]
I have some general questions about why CPU usage might spike when resuming training from a checkpoint:

Upon resuming training of a TQC agent from a saved checkpoint, we see that CPU usage is very high when the resumed training job has a batch size nearly double that of the training job that produced the checkpoint. 

More concretely, suppose a training job was run with a batch size of 256 and called `TQC.save('checkpoint1')` at some point during training. Then we resume training starting at `TQC.load('checkpoint1')` in two different jobs: (1) with batch size of 384 and (2) with batch size of 512. Our experience is that resumed job (2) with the batch size of 512 shows > 10x the CPU utilization as the original job and resumed job (1) with the batch size of 384:

- The original job and the resumed jobs have similar GPU usage
- If the resumed job isn't cpu bound, the training speed doesn't appear to change either

I am curious if there is anything about TQC specifically that would cause this type of behaviour, or if this is more likely to be caused by something at the pytorch level?

Sorry if this question doesn't belong here and thanks for all your work on stable-baselines3 and sb3-contrib!

**Comment by araffin** [comment]
Hello,
have you tried limiting the number of threads used by PyTorch?
https://github.com/DLR-RM/stable-baselines3/issues/283#issuecomment-755214753

And when do you see high cpu usage? during data collection or during policy update?

**Comment by bradleypick** [comment]
Sorry, I forgot about this.

Limiting the number of threads used by PyTorch remedied the problem.

Thanks!
