### ISSUE TITLE
Maskable RecurrentPPO

### ISSUE THREAD

**Issue by dylanprins** [Stable-Baselines-Team/stable-baselines3-contrib#76]
Hi!

I was wondering whether a Maskable Recurrent PPO would be laborious to implement?
Our model choses illigal actions during training and evaluation but we would really like to keep using the Recurrent policy.

Kind regards,
Dylan Prins

**Comment by dylanprins** [comment]
Hi!

Frame stacking does not work properly on our problem compared to using a recurrent implementation. Most probably due to the nature of our data.

We've implemented the Maskable Recurrent PPO by ourselves by merging mppo and rppo and it works great! :)

Kind regards,
Dylan Prins

**Comment by araffin** [comment]
good to hear =)
in case the implementation is public, i would be happy to add a link in our documentation ;)
