### ISSUE TITLE
Tensorboard logging every metrics except rollout/ep_rew_mean

### ISSUE THREAD

**Issue by didoMazz** [Stable-Baselines-Team/stable-baselines3-contrib#85]
Logging with Tensorboard during training with PPO.learn logs all the metrics except rollout/ep_rew_mean.
The metric(ep_rew_mean) is being printed correctly on the terminal during training. 

eval/mean_reward is printed and logged correctly on Tensorboard.

```python
    env = gym.make('gym_ess_grid/ESS-v1')
    check_env(env)

    eval_env = gym.make('gym_ess_grid/ESS-v1')

    eval_callback = EvalCallback(eval_env, best_model_save_path='./logs/',
                          log_path='./logs/', eval_freq=365*24*3*10,
                                 deterministic=True, render=False)
    checkpoint_callback = CheckpointCallback(save_freq=365*24*3*10, save_path=SAVE_DIR.as_posix())

    model = PPO('MlpPolicy', env, verbose=1, tensorboard_log = "./ess_grid_tensorboard/" )
    model.learn(total_timesteps=365*24*3*1000,callback= [checkpoint_callback, eval_callback])

```
check.env doesn't return any error.

Never had this problem before, with the v0 version of the environment it worked correctly.
The difference are some changes made to the gym env and the fact that now i have in the 
/envs folder two python files essgrid.py and essgrid2.py, both gym env are resigistered correctly.

Going back to a version of the repo with only essgrid.py the logging works correctly. 
I haven't tried yet to delete essgrid.py and unregister it, I will try it asap when my training session is finished.

**System Info**
 * Installed with pip
 * Stable-Baselines3 == 1.5.0
 * Gym version == 0.21.0
 
![terminal print](https://user-images.githubusercontent.com/105937911/178544686-8328034b-3775-40bd-bc4e-8eafe3c15b4c.png)
![folders and init](https://user-images.githubusercontent.com/105937911/178544698-d758938d-d7c0-4ff5-94c1-5dce05e8102a.png)
![metrics 1](https://user-images.githubusercontent.com/105937911/178544705-5d82dfbe-7cfe-4064-ae6f-f100610647c1.png)
![metrics 2](https://user-images.githubusercontent.com/105937911/178544708-fbb76983-eb16-452e-8a42-c62b02f289f6.png)

**Comment by araffin** [comment]
Hello,
my guess is that the plot is there but you should zoom out.

**Comment by didoMazz** [comment]
I can't zoom out because there is no data, if i select another run (PPO_1_real_cost) then i can zoom out and again no graph.
![zoomed out](https://user-images.githubusercontent.com/105937911/178597705-d6be5f7e-5ebd-409b-8cda-c39de62cd8b2.png)

**Comment by didoMazz** [comment]
Didn't change anything, now it works ahah
Thanks for the reply!
