### ISSUE TITLE
[BUG] TRPO Agent not working for Multi Discrete Action Space

### ISSUE THREAD

**Issue by Akashg475** [Stable-Baselines-Team/stable-baselines3-contrib#86]
Continuing  on #83. Line no. 691 in distribution.py is throwing error. 

![Screenshot 2022-07-13 at 11 27 49 AM](https://user-images.githubusercontent.com/30070587/178661325-c13b9f7b-ca4f-462c-9d94-b9536c7beea9.png)

![Screenshot 2022-07-13 at 11 29 30 AM](https://user-images.githubusercontent.com/30070587/178661505-f56feb92-b359-478b-92db-de46ee57220c.png)

ISSUE:
Rather than comparing the complete _ndarray_, individual elements are compared and _assert_ is throwing error.

**Comment by Akashg475** [comment]
Forgot to mention the distributions.py is coming from stable_baselines3/common/distributions.py"

**Comment by araffin** [comment]
fixed in https://github.com/DLR-RM/stable-baselines3/pull/958

please upgrade to latest sb3 and sb3 contrib version.
