### ISSUE TITLE
PPO-Recurrent Bug: Policy Arguments 'shared_lstm' and 'enable_critic_lstm' passed wrongly if using recurrent Cnn/MultiInput policies 

### ISSUE THREAD

**Issue by mlodel** [Stable-Baselines-Team/stable-baselines3-contrib#89]
**Describe the bug**
The policy classes [RecurrentActorCriticCnnPolicy](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/sb3_contrib/common/recurrent/policies.py#L424) and [RecurrentMultiInputActorCriticPolicy](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/sb3_contrib/common/recurrent/policies.py#L514) wrongly initialize its parent class 'RecurrentActorCriticPolicy' with regard to the arguments 'shared_lstm' and 'enable_critic_lstm'. The argument 'shared_lstm' is missing in the keyword arguments of the constructor method of both the CNN and Multi-Input policies and is also not passed to the parent class constructor using positional arguments. Thus the argument 'enable_critic_lstm' (as passed by policy_kwargs from the model class) is passed on the position of the argument 'shared_lstm' to the constructor method of 'RecurrentActorCriticPolicy'. Thus, when using one of the two subclass policies, the 'enable_critic_lstm' argument actually controls the 'shared_lstm' setting in the policy initialization, while 'shared_lstm' is either None or when passed, an error occurs.

**Code example**
```python
from sb3_contrib import RecurrentPPO

model = RecurrentPPO(
    "CnnLstmPolicy",
    "CarRacing-v0",
    verbose=1,
    policy_kwargs=dict(shared_lstm=True, enable_critic_lstm=False),
)
model.learn(5000)
```
This code gives the error: 
```
File ".../stable-baselines3-contrib/sb3_contrib/ppo_recurrent/ppo_recurrent.py", line 147, in _setup_model
    self.policy = self.policy_class(
TypeError: __init__() got an unexpected keyword argument 'shared_lstm'
```

This bug can be fixed by adding the 'shared_lstm' parameter in four positions, two for each of the subclass policies.

**Comment by araffin** [comment]
> thanks for reporting the bug, will be happy to receive a PR that fixes this issue =)

PS: If you don't plan to do a PR, please tell us so I will see when I can do it ;)

**Comment by mlodel** [comment]
Hi @araffin, thanks for the reply. I will submit a PR by today ;).

**Comment by mlodel** [comment]
I have a question before submitting the PR regarding tests (which I don't have much experience with):
I see that there is a [test](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/tests/test_lstm.py#L89) that is meant to detect a bug like this one, however it only does that for the MlpPolicy. Adding the two other policies to that specific test (as a test parameter) would probably make the [test_cnn](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/tests/test_lstm.py#L60) and [test_dict_obs](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/tests/test_lstm.py#L141) redundant. Would that be a problem? Thanks for the help!

**Comment by araffin** [comment]
It might be simpler to add cases to the others, but it's up to you, you can also add tests to that one https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/tests/test_lstm.py#L89
