### ISSUE TITLE
MaskableEvalCallback doesn't work with StopTrainingOnNoModelImprovement

### ISSUE THREAD

**Issue by CppMaster** [Stable-Baselines-Team/stable-baselines3-contrib#92]
**Describe the bug**
MaskableEvalCallback doesn't call StopTrainingOnNoModelImprovement. It's because it's only called on new best mean reward, instead of after every evaluation. In those cases StopTrainingOnNoModelImprovement always resets it's no_improvement_evals, so it never stops the training.
Currently, this is the end of the step of MaskableEvalCallback:
[MaskableEvalCallback ](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/3cbd2429be7cf94d40c72e1e8801743345999ace/sb3_contrib/common/maskable/callbacks.py#L97)
```python
            if mean_reward > self.best_mean_reward:
                if self.verbose > 0:
                    print("New best mean reward!")
                if self.best_model_save_path is not None:
                    self.model.save(os.path.join(self.best_model_save_path, "best_model"))
                self.best_mean_reward = mean_reward
                # Trigger callback if needed
                if self.callback is not None:
                    return self._on_event()
```
Instead it should call self.callback_on_new_best on new best mean reward instead and self.callback after every evaluation:
```python
            continue_training = True

            if mean_reward > self.best_mean_reward:
                if self.verbose > 0:
                    print("New best mean reward!")
                if self.best_model_save_path is not None:
                    self.model.save(os.path.join(self.best_model_save_path, "best_model"))
                self.best_mean_reward = mean_reward
                # Trigger callback on new best model, if needed
                if self.callback_on_new_best is not None:
                    continue_training = self.callback_on_new_best.on_step()

            # Trigger callback after every evaluation, if needed
            if self.callback is not None:
                continue_training &= self._on_event()

            return continue_training 
```
Just like in [EvalCallback](https://github.com/DLR-RM/stable-baselines3/blob/fda3d4d748439a6755260896e4350e0383a9c6f1/stable_baselines3/common/callbacks.py#L444)

**Code example**
```python
from sb3_contrib import MaskablePPO
from sb3_contrib.common.maskable.callbacks import MaskableEvalCallback
from stable_baselines3.common.callbacks import StopTrainingOnNoModelImprovement
from minigames.collect_minerals_and_gas.src.env_dicrete import CollectMineralAndGasDiscreteEnv


env = CollectMineralAndGasDiscreteEnv(step_mul=8, realtime=False)
stop_callback = StopTrainingOnNoModelImprovement(max_no_improvement_evals=10, min_evals=10, verbose=1)
eval_callback = MaskableEvalCallback(
    env, eval_freq=100000, deterministic=False, render=False, callback_after_eval=stop_callback, n_eval_episodes=20
)

model = MaskablePPO("MlpPolicy", env)
model.learn(10000000, callback=eval_callback)
```

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...) **PIP**
 * Stable-Baselines3 and sb3-contrib versions **1.5.0, contrib: 1.5.0**
 * GPU models and configuration **RTX 3070**
 * Python version **3.9.7**
 * PyTorch version **1.11.0+cu113**
 * Gym version **0.21.0**

**Comment by araffin** [comment]
Hello,
thanks for reporting the issue, we indeed forgot to update this callback.
I would welcome a PR that solves that issue =)

**Comment by CppMaster** [comment]
I've tried to push the changes on my feature branch, but I've got 404 permission denied. Do I need to be included as a member of the project?

**Comment by araffin** [comment]
> Do I need to be included as a member of the project?

You need to fork SB3 contrib and push to a feature branch, then you will be able to do a PR, and I will be able to push edits to it (please don't use master branch on your fork).
