### ISSUE TITLE
MaskableTrialEvalCallback - where to contribute

### ISSUE THREAD

**Issue by CppMaster** [Stable-Baselines-Team/stable-baselines3-contrib#94]
Hi,
I've created [MaskableTrialEvalCallback](https://github.com/CppMaster/SC2-AI/blob/master/optuna_utils/maskable_trial_eval_callback.py), which combines [TrialEvalCallback](https://github.com/DLR-RM/rl-baselines3-zoo/blob/f1064a7e8c4c19d6599e84fd73c684b158de1e56/utils/callbacks.py#L17) and [MaskableEvalCallback](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/sb3_contrib/common/maskable/callbacks.py). Those 2 are in different repositories, so I don't know in to which one I could contribute this one?

Does it makes sense to move callbacks.py and wrappers from [rl-baselines3-zoo](https://github.com/DLR-RM/rl-baselines3-zoo/tree/master/utils) to the contrib repo? I think there is a consensus that hyper-parameter search is essential in RL. Then it'd make sense to contribute MaskableTrialEvalCallback to this repo.

**Comment by araffin** [comment]
Hello,
good question.
I think this is related to https://github.com/DLR-RM/rl-baselines3-zoo/issues/249.
For now, I think I would welcome a PR in the RL Zoo (otherwise, we would need to add optuna as dependency for SB3 contrib).

> Does it makes sense to move callbacks.py and wrappers from [rl-baselines3-zoo](https://github.com/DLR-RM/rl-baselines3-zoo/tree/master/utils) to the contrib repo?

Originally, I had the plan to do that, but some wrappers/callbacks are very specific, so  now I'm not sure about that.
But if you think some of them must be part of SB3 contrib, I would welcome a PR that moves them to this repo ;) (we can discuss which ones here).

**Comment by CppMaster** [comment]
TrialEvalCallback only makes sense with Optuna and I don't know the rest.

Do you consider Optuna as a dependency problematic? If so, what's the biggest issue with that?

**Comment by araffin** [comment]
> Do you consider Optuna as a dependency problematic? If so, what's the biggest issue with that?

I mostly prefer to have minimal dependencies (and Optuna has many dependencies too). We could add optuna via an `optuna` keyword in the package installation.
The other thing is that for now, the optuna callback only makes sense with the RL Zoo infrastructure (all the optuna code that goes with it).

**Comment by CppMaster** [comment]
Hmm, yeah, you're right. TrialEvalCallback alone may not be a good enough reason to have Optuna as dependency. If some wants to use both Maskable and Optuna, he will just have to replicate MaskableTrialEvalCallback.

You probably also wouldn't want RL-zoo to be dependant on Contrib, right?

**Comment by araffin** [comment]
RL Zoo already depends on SB3 and contrib.

**Comment by CppMaster** [comment]
Oh, ok then.
