### ISSUE TITLE
ARS calling reset twice

### ISSUE THREAD

**Issue by SOGorman35** [Stable-Baselines-Team/stable-baselines3-contrib#95]
Describe how the library was installed: pip

sb3-contrib==1.5.1a9
Python: 3.9.12
Stable-Baselines3: 1.5.1a8
PyTorch: 1.11.0
GPU Enabled: False
Numpy: 1.22.4
Gym: 0.21.0

I'm using a custom environment that tracks the episode number, with 1 added to env.episode upon reset.  With literally every other model, this works fine, but in ARS, reset seems to be called twice in a row, so instead of episode 10 showing as episode 10, it will show as episode 20.  It is more of an inconvenience than anything else, and my workaround has been to just update the episode number when done == True instead, but I wasn't sure if reset being called twice is impacting the observations, etc. that the model is receiving.

**Comment by araffin** [comment]
Hello,
could you please give a minimal code to reproduce the issue?

This is actually a side effect of using `evaluate_policy` helper inside ARS. Between two updates, it forces the env to reset, but because the env was already reset (automatically because it is a `VecEnv`) then you observe a double reset.

For correct statistics, please use the values from the SB3 `Monitor` and logger.

**Comment by araffin** [comment]
> but I wasn't sure if reset being called twice is impacting the observations, etc. that the model is receiving.

Compared to other models, ARS does not reply on a buffer, so it has not impact on the training.

**Comment by SOGorman35** [comment]
here is the simplest env I could write:

`import gym
import numpy as np
import random

from sb3_contrib import ARS

class DummyEnv(gym.Env):
    
    metadata = {'render.modes' : ['human']}

    def __init__(self,):
        super(DummyEnv, self).__init__()
        
        self.action_space = gym.spaces.Discrete(2)
        self.observation_space = gym.spaces.Box(low=-np.inf,high=np.inf,shape=(1,))
        self.episode = 0
        self.total_steps = 10
        self.current_step = 0
        
    def _nextObservation(self):
    
        obs = random.randint(0,1)
        
        return obs
             
    def step(self, action):
        
        obs = self._nextObservation()
        self.current_step += 1
        reward = random.randint(0,1)
        if self.current_step == self.total_steps:
            done = True
        else:
            done = False
            
        print('step: {} obs: {} action: {}'.format(self.current_step,obs,reward))

        return obs, reward, done, {}
    
    def reset(self):
        
        self.current_step = 0
        self.episode += 1
        print('')
        print('EPISODE {}'.format(int(self.episode)))
        print('')
        
        return self._nextObservation()
    
model = ARS("MlpPolicy",DummyEnv())
model.learn(total_timesteps=100)`

And the output:

> Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.

> EPISODE 1


> EPISODE 2

> step: 1 obs: 0 action: 1
step: 2 obs: 1 action: 1
step: 3 obs: 0 action: 1
step: 4 obs: 1 action: 0
step: 5 obs: 1 action: 1
step: 6 obs: 1 action: 1
step: 7 obs: 0 action: 0
step: 8 obs: 0 action: 0
step: 9 obs: 1 action: 1
step: 10 obs: 0 action: 1

> EPISODE 3


> EPISODE 4

> step: 1 obs: 1 action: 0
step: 2 obs: 1 action: 1
step: 3 obs: 0 action: 0
step: 4 obs: 0 action: 1
step: 5 obs: 1 action: 1
step: 6 obs: 0 action: 0
step: 7 obs: 0 action: 1
step: 8 obs: 1 action: 0
step: 9 obs: 1 action: 1
step: 10 obs: 0 action: 1

> EPISODE 5


> EPISODE 6

>step: 1 obs: 1 action: 0
step: 2 obs: 1 action: 0
step: 3 obs: 0 action: 1
step: 4 obs: 1 action: 1
step: 5 obs: 0 action: 1
step: 6 obs: 1 action: 1
step: 7 obs: 0 action: 0
step: 8 obs: 1 action: 1
step: 9 obs: 1 action: 1
step: 10 obs: 0 action: 1

>EPISODE 7


> EPISODE 8

> step: 1 obs: 1 action: 0
step: 2 obs: 1 action: 0
step: 3 obs: 1 action: 0
step: 4 obs: 1 action: 1
step: 5 obs: 1 action: 1
step: 6 obs: 1 action: 1
step: 7 obs: 0 action: 1
step: 8 obs: 0 action: 1
step: 9 obs: 1 action: 1
step: 10 obs: 0 action: 1

> EPISODE 9


> EPISODE 10

> step: 1 obs: 0 action: 0
step: 2 obs: 1 action: 0
step: 3 obs: 1 action: 0
step: 4 obs: 0 action: 1
step: 5 obs: 1 action: 0
step: 6 obs: 0 action: 1
step: 7 obs: 1 action: 0
step: 8 obs: 0 action: 1
step: 9 obs: 1 action: 0
step: 10 obs: 0 action: 1

> EPISODE 11


> EPISODE 12

> step: 1 obs: 1 action: 0
step: 2 obs: 0 action: 1
step: 3 obs: 0 action: 1
step: 4 obs: 1 action: 0
step: 5 obs: 1 action: 1
step: 6 obs: 0 action: 1
step: 7 obs: 1 action: 0
step: 8 obs: 1 action: 0
step: 9 obs: 0 action: 0
step: 10 obs: 0 action: 0

>EPISODE 13


> EPISODE 14

> step: 1 obs: 1 action: 1
step: 2 obs: 1 action: 0
step: 3 obs: 1 action: 0
step: 4 obs: 0 action: 1
step: 5 obs: 0 action: 1
step: 6 obs: 1 action: 1
step: 7 obs: 1 action: 0
step: 8 obs: 0 action: 1
step: 9 obs: 1 action: 1
step: 10 obs: 1 action: 1

> EPISODE 15


> EPISODE 16

> step: 1 obs: 1 action: 0
step: 2 obs: 1 action: 1
step: 3 obs: 1 action: 0
step: 4 obs: 0 action: 0
step: 5 obs: 1 action: 1
step: 6 obs: 1 action: 1
step: 7 obs: 0 action: 0
step: 8 obs: 1 action: 1
step: 9 obs: 1 action: 0
step: 10 obs: 0 action: 1

> EPISODE 17


> EPISODE 18

> step: 1 obs: 1 action: 1
step: 2 obs: 1 action: 1
step: 3 obs: 0 action: 0
step: 4 obs: 0 action: 1
step: 5 obs: 0 action: 0
step: 6 obs: 0 action: 1
step: 7 obs: 1 action: 1
step: 8 obs: 1 action: 1
step: 9 obs: 0 action: 0
step: 10 obs: 1 action: 1

> EPISODE 19


> EPISODE 20

> step: 1 obs: 1 action: 1
step: 2 obs: 0 action: 1
step: 3 obs: 1 action: 0
step: 4 obs: 1 action: 1
step: 5 obs: 1 action: 0
step: 6 obs: 0 action: 0
step: 7 obs: 0 action: 0
step: 8 obs: 1 action: 1
step: 9 obs: 0 action: 0
step: 10 obs: 1 action: 1

> EPISODE 21


> EPISODE 22

> step: 1 obs: 0 action: 0
step: 2 obs: 1 action: 0
step: 3 obs: 0 action: 0
step: 4 obs: 1 action: 1
step: 5 obs: 0 action: 0
step: 6 obs: 1 action: 0
step: 7 obs: 0 action: 1
step: 8 obs: 0 action: 1
step: 9 obs: 1 action: 1
step: 10 obs: 1 action: 1

> EPISODE 23


> EPISODE 24

> step: 1 obs: 0 action: 0
step: 2 obs: 1 action: 1
step: 3 obs: 0 action: 0
step: 4 obs: 1 action: 1
step: 5 obs: 0 action: 1
step: 6 obs: 0 action: 0
step: 7 obs: 1 action: 0
step: 8 obs: 0 action: 0
step: 9 obs: 1 action: 1
step: 10 obs: 0 action: 1

> EPISODE 25


> EPISODE 26

> step: 1 obs: 0 action: 0
step: 2 obs: 1 action: 1
step: 3 obs: 1 action: 1
step: 4 obs: 1 action: 1
step: 5 obs: 0 action: 1
step: 6 obs: 1 action: 0
step: 7 obs: 1 action: 0
step: 8 obs: 1 action: 0
step: 9 obs: 0 action: 1
step: 10 obs: 0 action: 0

> EPISODE 27


> EPISODE 28

> step: 1 obs: 1 action: 0
step: 2 obs: 0 action: 0
step: 3 obs: 0 action: 1
step: 4 obs: 0 action: 1
step: 5 obs: 0 action: 1
step: 6 obs: 0 action: 0
step: 7 obs: 0 action: 0
step: 8 obs: 0 action: 1
step: 9 obs: 0 action: 0
step: 10 obs: 0 action: 0

> EPISODE 29


> EPISODE 30

> step: 1 obs: 0 action: 1
step: 2 obs: 0 action: 1
step: 3 obs: 1 action: 0
step: 4 obs: 1 action: 0
step: 5 obs: 1 action: 1
step: 6 obs: 1 action: 1
step: 7 obs: 1 action: 0
step: 8 obs: 0 action: 1
step: 9 obs: 0 action: 0
step: 10 obs: 1 action: 1

> EPISODE 31


> EPISODE 32

> step: 1 obs: 0 action: 1
step: 2 obs: 1 action: 0
step: 3 obs: 1 action: 1
step: 4 obs: 0 action: 0
step: 5 obs: 0 action: 0
step: 6 obs: 0 action: 1
step: 7 obs: 0 action: 1
step: 8 obs: 1 action: 0
step: 9 obs: 1 action: 0
step: 10 obs: 1 action: 1

> EPISODE 33

**Comment by araffin** [comment]
thanks for the code example (please format it with markdown codeblock next time), what is happening is exactly what i described.
